name: Periodic tasks

on:
  schedule:
    - cron: "0 3 */5 * *"
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Запустить задачу
        run: ./scripts/task.sh
